apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice.name }}-stage
  namespace: {{.Values.microservice.namespace}}
spec:
  type: {{.Values.microservice.service.type}}
  ports:
    - port: {{.Values.microservice.service.port}}
      targetPort: {{.Values.microservice.containerPort}}
      protocol: TCP
      name: http
  selector:
    app: {{.Values.microservice.name}}
    {{- if eq .Values.productionSlot "blue" }}
    slot: green
    {{- else }}
    slot: blue
    {{- end }}

